# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Mohammad Reza Taesiri'
description: ''

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
# facebook: ''
twitter: 'taesiri'
linkedin: 'taesiri/'
instagram: 'taesiri'
pinterest: 'mtaesiri'
youtube: 'UCPx-boVjDWNRzOkSE0_ctMw'
github-user: 'taesiri'
#codepen: ''
steam: 'mtaesiri'
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
reddit: 'taesiri'
medium:  'mtaesiri'
#tumblr: ''
# weibo: ''
# vk: ''
# blog_url: ''
email: 'mtaesiri@gmail.com'
# messenger: ''

# Advanced settings
plugins:
  - jekyll-remote-theme
